### ISSUE TITLE
Library should default to RDC collection instead of 2o7.net collection

### ISSUE THREAD

**Issue by marcus-robinson** [AdobeAtAdobe/adobe-analytics-di#17]
This library uses `xyz.112.2o7.net` as the default collection server (as opposed to `xzy.sc.omtrdc.net`), which means it's using the old configuration and is not Regional Data Collection (RDC) enabled. Sure, this can be overridden using the "setTrackingServerUrl" method to use an RDC endpoint, but sensible defaults should be used, rather than old legacy defaults.

There are many customers who had not transitioned to RDC, but wanted to implement server-side-forwarding using server-side Adobe Analytics. They had a lot of problems with it, especially, many unsuccessful calls. They transitioned to RDC and all these problems went away.

**Comment by dbenge** [comment]
Cool, do you have time to put in enhancement to the library to help us address that? It's a very old library so I have no doubt that it is falling behind.  Or what would you suggest to address this concern?

**Comment by dbenge** [comment]
changed in version 1.3.4
