### ISSUE TITLE
Broken Docs Link in Readme

### ISSUE THREAD

**Issue by marcus-robinson** [AdobeAtAdobe/adobe-analytics-di#18]
At the moment, the docs link to a dead page https://marketing.adobe.com/developer/documentation/data-insertion/c-data-insertion-api

This should instead link to the DI XML spec:
https://github.com/AdobeDocs/analytics-1.4-apis/blob/master/docs/data-insertion-api/index.md

**Comment by davidbenge** [comment]
fixed in next pr
