### ISSUE TITLE
pageName shouldn't always be mandatory

### ISSUE THREAD

**Issue by marcus-robinson** [AdobeAtAdobe/adobe-analytics-di#19]
The library currently makes pageName mandatory. However, as the [XML API spec states](https://github.com/AdobeDocs/analytics-1.4-apis/blob/master/docs/data-insertion-api/reference/r_supported_tags.md):

> to specify that a given row should be considered a page view, that row must contain either `pageName` or `pageURL`. To specify that a given row should be considered a link event, that row must include `linkType` and either `linkName` or `linkURL`. If a given row contains both `linkType` and either `pageName` or `pageURL`, Adobe Analytics will automatically clear out `pageName` and `pageURL` by setting them to null.

We are using the library purely for link event tracking, so we don't need to pass pageView and yet the library forces us. As it is if we somehow end up with an accidentally undefined linkName the lib will fall back to using the pageName value.

The validation should be smart enough to handle these scenarios.

**Comment by davidbenge** [comment]
I commented out the pageName or pageUrl check
