### ISSUE TITLE
Incorrect validation of mandatory visitorId

### ISSUE THREAD

**Issue by marcus-robinson** [AdobeAtAdobe/adobe-analytics-di#20]
[This code](https://github.com/AdobeAtAdobe/adobe-analytics-di/blob/master/index.js#L262) enforces that either ip or visitor is defined and throws an error if both are undefined.

This is incorrect. As per the [AA docs](https://docs.adobe.com/content/help/en/analytics/components/metrics/unique-visitors.html), marketingCloudVisitorID is a valid visitor identification method. 

Errors should not be thrown if the marketingCloudVisitorID is defined.

**Comment by marcus-robinson** [comment]
In fact, we've found that by passing `visitorId` in the payload, `marketingCloudVisitorID` is completely ignored! We need AA to recognise ECID, so we've had to patch this library ourselves to bypass the validation that forces the mandatory `visitorId`.

**Comment by davidbenge** [comment]
so if visitorId is defined and marketingCloudVisitorID is defined 
marketingCloudVisitorID gets ignored?
marketingCloudVisitorID should have precedence over visitorId?
